sudo: required
dist: trusty
language: node_js
node_js:
  - 8
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
script:
  - npm run build:prod
  - npm run test:travis

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start