export let loading = {
  'dire_team_name': 'Dire',
  'league': {
    'league_id': 1234,
    'name': 'Loading...',
    'tournament_url': ''
  },
  'match_id': 1234567890,
  'radiant_team_name': 'Radiant',
  'scoreboard': {
    'day_cycle': 'day',
    'did_game_start': true,
    'dire': {
      'bans': [
        'None',
        'None',
        'None',
        'None',
        'None'
      ],
      'barracks_state': '111111',
      'picks': [
        'None',
        'None',
        'None',
        'None',
        'None'
      ],
      'players': [
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        }
      ],
      'score': 0,
      'tower_state': '11111111111'
    },
    'duration': 0,
    'radiant': {
      'bans': [
        'None',
        'None',
        'None',
        'None',
        'None'
      ],
      'barracks_state': '111111',
      'picks': [
        'None',
        'None',
        'None',
        'None',
        'None'
      ],
      'players': [
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        },
        {
          'account_id': 1234567890,
          'assists': 0,
          'death': 0,
          'denies': 0,
          'gold': 0,
          'gold_per_min': 0,
          'hero': 'None',
          'items': [
            'None',
            'None',
            'None',
            'None',
            'None',
            'None'
          ],
          'kills': 0,
          'last_hits': 0,
          'level': 1,
          'name': '',
          'net_worth': 625,
          'player_slot': 1,
          'position_x': 0,
          'position_y': 0,
          'respawn_timer': 0,
          'ultimate_cooldown': 0,
          'ultimate_state': 0,
          'xp_per_min': 0,
          'team': 'dire'
        }
      ],
      'score': 0,
      'tower_state': '11111111111'
    },
    'roshan_respawn_timer': 0
  },
  'series': {
    'dire_series_wins': [
      -1
    ],
    'radiant_series_wins': [
      -1
    ]
  },
  'spectators': 0,
  'stream_delay_s': 0
};
