export let loadingMmr = {
  "average_mmr": 0,
  "delay": 0,
  "dire_score": 0,
  "game_time": 1,
  "lobby_id": "0",
  "players": [
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    },
    {
      "assists": 0,
      "deaths": 0,
      "dh": 0,
      "hero": "None",
      "kills": 0,
      "level": 0,
      "lh": 0,
      "name": "",
      "x": 0,
      "y": 0
    }
  ],
  "radiant_score": 0,
  "server_steam_id": "0",
  "spectators": 0,
  "$key": "0"
}
