import requests

# grab hero images
def main():
  for hero in hero_links:
    response = requests.get(hero_links[hero])
    if response.status_code == 200:
      f = open('E:\\Projects\\dota2-ms-server\\hero_images\\items\\{0}_hphover.png'.format(hero), 'wb')
      f.write(response.content)
      f.close()
    else:
      print('not found')

hero_links = {
  "monkey_king": "http://cdn.dota2.com/apps/dota2/images/heroes/monkey_king_hphover.png",
  "lone_druid": "http://cdn.dota2.com/apps/dota2/images/heroes/lone_druid_hphover.png",
  "naga_siren": "http://cdn.dota2.com/apps/dota2/images/heroes/naga_siren_hphover.png",
  "enigma": "http://cdn.dota2.com/apps/dota2/images/heroes/enigma_hphover.png",
  "skeleton_king": "http://cdn.dota2.com/apps/dota2/images/heroes/skeleton_king_hphover.png",
  "sven": "http://cdn.dota2.com/apps/dota2/images/heroes/sven_hphover.png",
  "antimage": "http://cdn.dota2.com/apps/dota2/images/heroes/antimage_hphover.png",
  "visage": "http://cdn.dota2.com/apps/dota2/images/heroes/visage_hphover.png",
  "luna": "http://cdn.dota2.com/apps/dota2/images/heroes/luna_hphover.png",
  "ogre_magi": "http://cdn.dota2.com/apps/dota2/images/heroes/ogre_magi_hphover.png",
  "juggernaut": "http://cdn.dota2.com/apps/dota2/images/heroes/juggernaut_hphover.png",
  "clinkz": "http://cdn.dota2.com/apps/dota2/images/heroes/clinkz_hphover.png",
  "oracle": "http://cdn.dota2.com/apps/dota2/images/heroes/oracle_hphover.png",
  "elder_titan": "http://cdn.dota2.com/apps/dota2/images/heroes/elder_titan_hphover.png",
  "chen": "http://cdn.dota2.com/apps/dota2/images/heroes/chen_hphover.png",
  "disruptor": "http://cdn.dota2.com/apps/dota2/images/heroes/disruptor_hphover.png",
  "kunkka": "http://cdn.dota2.com/apps/dota2/images/heroes/kunkka_hphover.png",
  "lina": "http://cdn.dota2.com/apps/dota2/images/heroes/lina_hphover.png",
  "bristleback": "http://cdn.dota2.com/apps/dota2/images/heroes/bristleback_hphover.png",
  "tidehunter": "http://cdn.dota2.com/apps/dota2/images/heroes/tidehunter_hphover.png",
  "razor": "http://cdn.dota2.com/apps/dota2/images/heroes/razor_hphover.png",
  "gyrocopter": "http://cdn.dota2.com/apps/dota2/images/heroes/gyrocopter_hphover.png",
  "bane": "http://cdn.dota2.com/apps/dota2/images/heroes/bane_hphover.png",
  "earthshaker": "http://cdn.dota2.com/apps/dota2/images/heroes/earthshaker_hphover.png",
  "templar_assassin": "http://cdn.dota2.com/apps/dota2/images/heroes/templar_assassin_hphover.png",
  "medusa": "http://cdn.dota2.com/apps/dota2/images/heroes/medusa_hphover.png",
  "jakiro": "http://cdn.dota2.com/apps/dota2/images/heroes/jakiro_hphover.png",
  "doom_bringer": "http://cdn.dota2.com/apps/dota2/images/heroes/doom_bringer_hphover.png",
  "lich": "http://cdn.dota2.com/apps/dota2/images/heroes/lich_hphover.png",
  "crystal_maiden": "http://cdn.dota2.com/apps/dota2/images/heroes/crystal_maiden_hphover.png",
  "arc_warden": "http://cdn.dota2.com/apps/dota2/images/heroes/arc_warden_hphover.png",
  "phantom_lancer": "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_lancer_hphover.png",
  "rattletrap": "http://cdn.dota2.com/apps/dota2/images/heroes/rattletrap_hphover.png",
  "death_prophet": "http://cdn.dota2.com/apps/dota2/images/heroes/death_prophet_hphover.png",
  "batrider": "http://cdn.dota2.com/apps/dota2/images/heroes/batrider_hphover.png",
  "abaddon": "http://cdn.dota2.com/apps/dota2/images/heroes/abaddon_hphover.png",
  "night_stalker": "http://cdn.dota2.com/apps/dota2/images/heroes/night_stalker_hphover.png",
  "winter_wyvern": "http://cdn.dota2.com/apps/dota2/images/heroes/winter_wyvern_hphover.png",
  "dazzle": "http://cdn.dota2.com/apps/dota2/images/heroes/dazzle_hphover.png",
  "weaver": "http://cdn.dota2.com/apps/dota2/images/heroes/weaver_hphover.png",
  "slark": "http://cdn.dota2.com/apps/dota2/images/heroes/slark_hphover.png",
  "ursa": "http://cdn.dota2.com/apps/dota2/images/heroes/ursa_hphover.png",
  "axe": "http://cdn.dota2.com/apps/dota2/images/heroes/axe_hphover.png",
  "puck": "http://cdn.dota2.com/apps/dota2/images/heroes/puck_hphover.png",
  "lion": "http://cdn.dota2.com/apps/dota2/images/heroes/lion_hphover.png",
  "tusk": "http://cdn.dota2.com/apps/dota2/images/heroes/tusk_hphover.png",
  "spectre": "http://cdn.dota2.com/apps/dota2/images/heroes/spectre_hphover.png",
  "bloodseeker": "http://cdn.dota2.com/apps/dota2/images/heroes/bloodseeker_hphover.png",
  "rubick": "http://cdn.dota2.com/apps/dota2/images/heroes/rubick_hphover.png",
  "undying": "http://cdn.dota2.com/apps/dota2/images/heroes/undying_hphover.png",
  "silencer": "http://cdn.dota2.com/apps/dota2/images/heroes/silencer_hphover.png",
  "shredder": "http://cdn.dota2.com/apps/dota2/images/heroes/shredder_hphover.png",
  "troll_warlord": "http://cdn.dota2.com/apps/dota2/images/heroes/troll_warlord_hphover.png",
  "queenofpain": "http://cdn.dota2.com/apps/dota2/images/heroes/queenofpain_hphover.png",
  "enchantress": "http://cdn.dota2.com/apps/dota2/images/heroes/enchantress_hphover.png",
  "storm_spirit": "http://cdn.dota2.com/apps/dota2/images/heroes/storm_spirit_hphover.png",
  "ancient_apparition": "http://cdn.dota2.com/apps/dota2/images/heroes/ancient_apparition_hphover.png",
  "leshrac": "http://cdn.dota2.com/apps/dota2/images/heroes/leshrac_hphover.png",
  "zuus": "http://cdn.dota2.com/apps/dota2/images/heroes/zuus_hphover.png",
  "pugna": "http://cdn.dota2.com/apps/dota2/images/heroes/pugna_hphover.png",
  "ember_spirit": "http://cdn.dota2.com/apps/dota2/images/heroes/ember_spirit_hphover.png",
  "earth_spirit": "http://cdn.dota2.com/apps/dota2/images/heroes/earth_spirit_hphover.png",
  "bounty_hunter": "http://cdn.dota2.com/apps/dota2/images/heroes/bounty_hunter_hphover.png",
  "chaos_knight": "http://cdn.dota2.com/apps/dota2/images/heroes/chaos_knight_hphover.png",
  "huskar": "http://cdn.dota2.com/apps/dota2/images/heroes/huskar_hphover.png",
  "wisp": "http://cdn.dota2.com/apps/dota2/images/heroes/wisp_hphover.png",
  "magnataur": "http://cdn.dota2.com/apps/dota2/images/heroes/magnataur_hphover.png",
  "meepo": "http://cdn.dota2.com/apps/dota2/images/heroes/meepo_hphover.png",
  "spirit_breaker": "http://cdn.dota2.com/apps/dota2/images/heroes/spirit_breaker_hphover.png",
  "dragon_knight": "http://cdn.dota2.com/apps/dota2/images/heroes/dragon_knight_hphover.png",
  "warlock": "http://cdn.dota2.com/apps/dota2/images/heroes/warlock_hphover.png",
  "phoenix": "http://cdn.dota2.com/apps/dota2/images/heroes/phoenix_hphover.png",
  "sniper": "http://cdn.dota2.com/apps/dota2/images/heroes/sniper_hphover.png",
  "shadow_demon": "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_demon_hphover.png",
  "techies": "http://cdn.dota2.com/apps/dota2/images/heroes/techies_hphover.png",
  "legion_commander": "http://cdn.dota2.com/apps/dota2/images/heroes/legion_commander_hphover.png",
  "riki": "http://cdn.dota2.com/apps/dota2/images/heroes/riki_hphover.png",
  "tinker": "http://cdn.dota2.com/apps/dota2/images/heroes/tinker_hphover.png",
  "life_stealer": "http://cdn.dota2.com/apps/dota2/images/heroes/life_stealer_hphover.png",
  "pudge": "http://cdn.dota2.com/apps/dota2/images/heroes/pudge_hphover.png",
  "centaur": "http://cdn.dota2.com/apps/dota2/images/heroes/centaur_hphover.png",
  "nyx_assassin": "http://cdn.dota2.com/apps/dota2/images/heroes/nyx_assassin_hphover.png",
  "lycan": "http://cdn.dota2.com/apps/dota2/images/heroes/lycan_hphover.png",
  "dark_seer": "http://cdn.dota2.com/apps/dota2/images/heroes/dark_seer_hphover.png",
  "witch_doctor": "http://cdn.dota2.com/apps/dota2/images/heroes/witch_doctor_hphover.png",
  "keeper_of_the_light": "http://cdn.dota2.com/apps/dota2/images/heroes/keeper_of_the_light_hphover.png",
  "vengefulspirit": "http://cdn.dota2.com/apps/dota2/images/heroes/vengefulspirit_hphover.png",
  "treant": "http://cdn.dota2.com/apps/dota2/images/heroes/treant_hphover.png",
  "alchemist": "http://cdn.dota2.com/apps/dota2/images/heroes/alchemist_hphover.png",
  "drow_ranger": "http://cdn.dota2.com/apps/dota2/images/heroes/drow_ranger_hphover.png",
  "venomancer": "http://cdn.dota2.com/apps/dota2/images/heroes/venomancer_hphover.png",
  "broodmother": "http://cdn.dota2.com/apps/dota2/images/heroes/broodmother_hphover.png",
  "omniknight": "http://cdn.dota2.com/apps/dota2/images/heroes/omniknight_hphover.png",
  "phantom_assassin": "http://cdn.dota2.com/apps/dota2/images/heroes/phantom_assassin_hphover.png",
  "faceless_void": "http://cdn.dota2.com/apps/dota2/images/heroes/faceless_void_hphover.png",
  "brewmaster": "http://cdn.dota2.com/apps/dota2/images/heroes/brewmaster_hphover.png",
  "slardar": "http://cdn.dota2.com/apps/dota2/images/heroes/slardar_hphover.png",
  "viper": "http://cdn.dota2.com/apps/dota2/images/heroes/viper_hphover.png",
  "terrorblade": "http://cdn.dota2.com/apps/dota2/images/heroes/terrorblade_hphover.png",
  "invoker": "http://cdn.dota2.com/apps/dota2/images/heroes/invoker_hphover.png",
  "skywrath_mage": "http://cdn.dota2.com/apps/dota2/images/heroes/skywrath_mage_hphover.png",
  "furion": "http://cdn.dota2.com/apps/dota2/images/heroes/furion_hphover.png",
  "mirana": "http://cdn.dota2.com/apps/dota2/images/heroes/mirana_hphover.png",
  "nevermore": "http://cdn.dota2.com/apps/dota2/images/heroes/nevermore_hphover.png",
  "obsidian_destroyer": "http://cdn.dota2.com/apps/dota2/images/heroes/obsidian_destroyer_hphover.png",
  "beastmaster": "http://cdn.dota2.com/apps/dota2/images/heroes/beastmaster_hphover.png",
  "sand_king": "http://cdn.dota2.com/apps/dota2/images/heroes/sand_king_hphover.png",
  "morphling": "http://cdn.dota2.com/apps/dota2/images/heroes/morphling_hphover.png",
  "tiny": "http://cdn.dota2.com/apps/dota2/images/heroes/tiny_hphover.png",
  "windrunner": "http://cdn.dota2.com/apps/dota2/images/heroes/windrunner_hphover.png",
  "necrolyte": "http://cdn.dota2.com/apps/dota2/images/heroes/necrolyte_hphover.png",
  "shadow_shaman": "http://cdn.dota2.com/apps/dota2/images/heroes/shadow_shaman_hphover.png"
}

main()